Backend/Models/PokemonView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Domain;

namespace Backend.Models
{
    public class PokemonView:Pokemon
    {
        [Display(Name = "Sprite")]
        public HttpPostedFileBase SpriteFile { get; set; }
    }
}

Backend/Controllers/PokemonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Backend.Models;
using Domain;
using PsTools;

namespace Backend.Controllers
{
    public class PokemonsController : Controller
    {
        private readonly DataContext _db = new DataContext();

        // GET: Pokemons
        public async Task<ActionResult> Index()
        {
            return View(await _db.Pokemons.ToListAsync());
        }

        // GET: Pokemons/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pokemon pokemon = await _db.Pokemons.FindAsync(id);
            if (pokemon == null)
            {
                return HttpNotFound();
            }
            return View(pokemon);
        }

        // GET: Pokemons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pokemons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PokemonView view)
        {
            if (ModelState.IsValid)
            {

                var pokemon = new Pokemon
                {
                    Name = view.Name,
                    Abilities = view.Abilities,
                    LocationLat = view.LocationLat,
                    LocationLong = view.LocationLong,
                    Moves = view.Moves,
                    PokedexNumber = view.PokedexNumber,
                    Sprite = view.Sprite,Types= view.Types
                };

                var pic = string.Empty;
                var folder = "~/Content/Pokemons";

                if (view.SpriteFile != null)
                {
                    pic = Files.UploadPhoto(view.SpriteFile, folder, "");
                    pic = string.Format("{0}/{1}", folder, pic);
                }
                pokemon.Sprite = pic;
                _db.Pokemons.Add(pokemon);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        // GET: Pokemons/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pokemon = await _db.Pokemons.FindAsync(id);
            if (pokemon == null)
            {
                return HttpNotFound();
            }
            return View(pokemon);
        }

        // POST: Pokemons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( Pokemon pokemon)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(pokemon).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(pokemon);
        }

        // GET: Pokemons/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pokemon pokemon = await _db.Pokemons.FindAsync(id);
            if (pokemon == null)
            {
                return HttpNotFound();
            }
            return View(pokemon);
        }

        // POST: Pokemons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Pokemon pokemon = await _db.Pokemons.FindAsync(id);
            _db.Pokemons.Remove(pokemon);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Backend/Views/Pokemons/Create.cshtml
@model Backend.Models.PokemonView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Pokemons", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PokedexNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PokedexNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PokedexNumber, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.SpriteFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="file-input-new">
                <div class="input-group" style="width:280px">
                    <div tabindex="500" class="form-control file-caption">
                        <div class="file-caption-name" id="NombreArchivo">
                        </div>
                    </div>
                    <div class="input-group-btn" style="height:auto">
                        <div tabindex="500" class="btn btn-primary btn-file">
                            <i class="glyphicon glyphicon-folder-open"></i>
                            File Search...
                            @Html.TextBoxFor(modelo => modelo.SpriteFile, new { type = "file", id = "files" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Types, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Types, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Types, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Moves, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Moves, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Moves, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Abilities, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Abilities, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Abilities, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationLat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LocationLat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LocationLat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationLong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LocationLong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LocationLong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Pokemons/Delete.cshtml
@model Domain.Pokemon

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pokemon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PokedexNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PokedexNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sprite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sprite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Types)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Types)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moves)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moves)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abilities)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abilities)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLong)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Backend/Views/Pokemons/Details.cshtml
@model Domain.Pokemon

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pokemon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PokedexNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PokedexNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sprite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sprite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Types)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Types)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moves)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moves)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abilities)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abilities)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationLong)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PokemonId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backend/Views/Pokemons/Edit.cshtml
@model Domain.Pokemon

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pokemon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PokemonId)

        <div class="form-group">
            @Html.LabelFor(model => model.PokedexNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PokedexNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PokedexNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sprite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sprite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sprite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Types, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Types, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Types, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moves, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moves, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Moves, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abilities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abilities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abilities, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationLat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationLat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationLat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationLong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocationLong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocationLong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Pokemons/Index.cshtml
@model IEnumerable<Domain.Pokemon>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PokedexNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sprite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Types)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Moves)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Abilities)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocationLat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocationLong)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PokedexNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sprite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Types)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moves)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abilities)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocationLat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocationLong)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PokemonId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PokemonId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PokemonId })
        </td>
    </tr>
}

</table>